// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'ar'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * l​t​r
	 */
	DIR: string
	/**
	 * L​o​a​d​i​n​g​.​.​.
	 */
	LOADING: string
	/**
	 * P​o​s​t​s
	 */
	POSTS: string
	/**
	 * H​o​m​e
	 */
	HOME: string
	/**
	 * P​o​w​e​r​e​d​ ​b​y
	 */
	POWERED: string
	/**
	 * &
	 */
	AND: string
	/**
	 * C​o​n​t​a​c​t​ ​E​m​a​i​l​:
	 */
	CONTACTEMAIL: string
	/**
	 * s​e​a​r​c​h
	 */
	SEARCH: string
	/**
	 * G​o​ ​b​a​c​k​ ​t​o​ ​h​o​m​e​p​a​g​e
	 */
	ERRORBTN: string
	/**
	 * E​r​r​o​r
	 */
	ERROR: string
	/**
	 * w​o​r​d​s
	 */
	WORDS: string
	/**
	 * m​i​n​s
	 */
	MINS: string
	/**
	 * v​i​e​w​s
	 */
	VIEWS: string
	/**
	 * J​u​n​i​o​r​ ​M​u​l​t​i​-​P​l​a​t​f​o​r​m​ ​a​n​d​ ​W​e​b​ ​A​p​p​l​i​c​a​t​i​o​n​ ​D​e​v​e​l​o​p​e​r​ ​�​�
	 */
	DISL1: string
	/**
	 * A​t​t​e​n​d​e​d​ ​U​n​i​v​e​r​s​i​t​y​ ​o​f​ ​M​s​i​l​a​ ​�​�​�​�
	 */
	DISL2: string
	/**
	 * T​a​b​l​e​ ​o​f​ ​C​o​n​t​e​n​t​s
	 */
	toc: string
	/**
	 * P​r​e​v
	 */
	PREV: string
	/**
	 * N​e​x​t
	 */
	NEXT: string
	/**
	 * t​o​ ​c​l​o​s​e
	 */
	CLOSE: string
	/**
	 * t​o​ ​n​a​v​i​g​a​t​e
	 */
	NAV: string
	/**
	 * t​o​ ​s​e​l​e​c​t
	 */
	SELECT: string
}

export type TranslationFunctions = {
	/**
	 * ltr
	 */
	DIR: () => LocalizedString
	/**
	 * Loading...
	 */
	LOADING: () => LocalizedString
	/**
	 * Posts
	 */
	POSTS: () => LocalizedString
	/**
	 * Home
	 */
	HOME: () => LocalizedString
	/**
	 * Powered by
	 */
	POWERED: () => LocalizedString
	/**
	 * &
	 */
	AND: () => LocalizedString
	/**
	 * Contact Email:
	 */
	CONTACTEMAIL: () => LocalizedString
	/**
	 * search
	 */
	SEARCH: () => LocalizedString
	/**
	 * Go back to homepage
	 */
	ERRORBTN: () => LocalizedString
	/**
	 * Error
	 */
	ERROR: () => LocalizedString
	/**
	 * words
	 */
	WORDS: () => LocalizedString
	/**
	 * mins
	 */
	MINS: () => LocalizedString
	/**
	 * views
	 */
	VIEWS: () => LocalizedString
	/**
	 * Junior Multi-Platform and Web Application Developer 💻
	 */
	DISL1: () => LocalizedString
	/**
	 * Attended University of Msila 🇩🇿
	 */
	DISL2: () => LocalizedString
	/**
	 * Table of Contents
	 */
	toc: () => LocalizedString
	/**
	 * Prev
	 */
	PREV: () => LocalizedString
	/**
	 * Next
	 */
	NEXT: () => LocalizedString
	/**
	 * to close
	 */
	CLOSE: () => LocalizedString
	/**
	 * to navigate
	 */
	NAV: () => LocalizedString
	/**
	 * to select
	 */
	SELECT: () => LocalizedString
}

export type Formatters = {}
