// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'ar'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * l​t​r
	 */
	DIR: string
	/**
	 * L​o​a​d​i​n​g​.​.​.
	 */
	LOADING: string
	/**
	 * P​o​s​t​s
	 */
	POSTS: string
	/**
	 * A​l​l​ ​P​o​s​t​s
	 */
	ALLPOSTS: string
	/**
	 * H​o​m​e
	 */
	HOME: string
	/**
	 * P​o​w​e​r​e​d​ ​b​y
	 */
	POWERED: string
	/**
	 * &
	 */
	AND: string
	/**
	 * C​o​n​t​a​c​t​ ​E​m​a​i​l​:
	 */
	CONTACTEMAIL: string
	/**
	 * s​e​a​r​c​h
	 */
	SEARCH: string
	/**
	 * G​o​ ​b​a​c​k​ ​t​o​ ​h​o​m​e​p​a​g​e
	 */
	ERRORBTN: string
	/**
	 * E​r​r​o​r
	 */
	ERROR: string
	/**
	 * w​o​r​d​s
	 */
	WORDS: string
	/**
	 * m​i​n​s
	 */
	MINS: string
	/**
	 * v​i​e​w​s
	 */
	VIEWS: string
	/**
	 * J​u​n​i​o​r​ ​M​u​l​t​i​-​P​l​a​t​f​o​r​m​ ​a​n​d​ ​W​e​b​ ​A​p​p​l​i​c​a​t​i​o​n​ ​D​e​v​e​l​o​p​e​r​ ​�​�
	 */
	DISL1: string
	/**
	 * A​t​t​e​n​d​e​d​ ​U​n​i​v​e​r​s​i​t​y​ ​o​f​ ​M​s​i​l​a​ ​�​�​�​�
	 */
	DISL2: string
	/**
	 * T​a​b​l​e​ ​o​f​ ​C​o​n​t​e​n​t​s
	 */
	toc: string
	/**
	 * P​r​e​v
	 */
	PREV: string
	/**
	 * N​e​x​t
	 */
	NEXT: string
	/**
	 * t​o​ ​c​l​o​s​e
	 */
	CLOSE: string
	/**
	 * t​o​ ​n​a​v​i​g​a​t​e
	 */
	NAV: string
	/**
	 * t​o​ ​s​e​l​e​c​t
	 */
	SELECT: string
	/**
	 * F​o​u​n​d​ ​a​ ​m​i​s​t​a​k​e​?
	 */
	EDITTITLE: string
	/**
	 * E​v​e​r​y​ ​p​o​s​t​ ​i​s​ ​a​ ​M​a​r​k​d​o​w​n​ ​f​i​l​e​ ​s​o​ ​c​o​n​t​r​i​b​u​t​i​n​g​ ​i​s​ ​s​i​m​p​l​e​ ​a​s​ ​f​o​l​l​o​w​i​n​g​ ​t​h​e​ ​l​i​n​k​ ​b​e​l​o​w​ ​a​n​d​ ​p​r​e​s​s​i​n​g​ ​t​h​e​ ​p​e​n​c​i​l​ ​i​c​o​n​ ​i​n​s​i​d​e​ ​G​i​t​H​u​b​ ​t​o​ ​e​d​i​t​ ​i​t​.
	 */
	EDITDESC: string
	/**
	 * E​d​i​t​ ​o​n​ ​G​i​t​H​u​b
	 */
	EDITLINK: string
}

export type TranslationFunctions = {
	/**
	 * ltr
	 */
	DIR: () => LocalizedString
	/**
	 * Loading...
	 */
	LOADING: () => LocalizedString
	/**
	 * Posts
	 */
	POSTS: () => LocalizedString
	/**
	 * All Posts
	 */
	ALLPOSTS: () => LocalizedString
	/**
	 * Home
	 */
	HOME: () => LocalizedString
	/**
	 * Powered by
	 */
	POWERED: () => LocalizedString
	/**
	 * &
	 */
	AND: () => LocalizedString
	/**
	 * Contact Email:
	 */
	CONTACTEMAIL: () => LocalizedString
	/**
	 * search
	 */
	SEARCH: () => LocalizedString
	/**
	 * Go back to homepage
	 */
	ERRORBTN: () => LocalizedString
	/**
	 * Error
	 */
	ERROR: () => LocalizedString
	/**
	 * words
	 */
	WORDS: () => LocalizedString
	/**
	 * mins
	 */
	MINS: () => LocalizedString
	/**
	 * views
	 */
	VIEWS: () => LocalizedString
	/**
	 * Junior Multi-Platform and Web Application Developer 💻
	 */
	DISL1: () => LocalizedString
	/**
	 * Attended University of Msila 🇩🇿
	 */
	DISL2: () => LocalizedString
	/**
	 * Table of Contents
	 */
	toc: () => LocalizedString
	/**
	 * Prev
	 */
	PREV: () => LocalizedString
	/**
	 * Next
	 */
	NEXT: () => LocalizedString
	/**
	 * to close
	 */
	CLOSE: () => LocalizedString
	/**
	 * to navigate
	 */
	NAV: () => LocalizedString
	/**
	 * to select
	 */
	SELECT: () => LocalizedString
	/**
	 * Found a mistake?
	 */
	EDITTITLE: () => LocalizedString
	/**
	 * Every post is a Markdown file so contributing is simple as following the link below and pressing the pencil icon inside GitHub to edit it.
	 */
	EDITDESC: () => LocalizedString
	/**
	 * Edit on GitHub
	 */
	EDITLINK: () => LocalizedString
}

export type Formatters = {}
